package cap.mvc.model;

public class Classmate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmate.STU_NMB
     *
     * @mbg.generated
     */
    private Integer stuNmb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmate.PAGE_ID
     *
     * @mbg.generated
     */
    private Long pageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmate.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmate.NICKNAME
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmate.PWD
     *
     * @mbg.generated
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmate.DSC
     *
     * @mbg.generated
     */
    private String dsc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmate.AUTHORITY
     *
     * @mbg.generated
     */
    private Integer authority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classmate.HEAD_IMG
     *
     * @mbg.generated
     */
    private String headImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmate.STU_NMB
     *
     * @return the value of classmate.STU_NMB
     *
     * @mbg.generated
     */
    public Integer getStuNmb() {
        return stuNmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmate.STU_NMB
     *
     * @param stuNmb the value for classmate.STU_NMB
     *
     * @mbg.generated
     */
    public void setStuNmb(Integer stuNmb) {
        this.stuNmb = stuNmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmate.PAGE_ID
     *
     * @return the value of classmate.PAGE_ID
     *
     * @mbg.generated
     */
    public Long getPageId() {
        return pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmate.PAGE_ID
     *
     * @param pageId the value for classmate.PAGE_ID
     *
     * @mbg.generated
     */
    public void setPageId(Long pageId) {
        this.pageId = pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmate.NAME
     *
     * @return the value of classmate.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmate.NAME
     *
     * @param name the value for classmate.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmate.NICKNAME
     *
     * @return the value of classmate.NICKNAME
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmate.NICKNAME
     *
     * @param nickname the value for classmate.NICKNAME
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmate.PWD
     *
     * @return the value of classmate.PWD
     *
     * @mbg.generated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmate.PWD
     *
     * @param pwd the value for classmate.PWD
     *
     * @mbg.generated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmate.DSC
     *
     * @return the value of classmate.DSC
     *
     * @mbg.generated
     */
    public String getDsc() {
        return dsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmate.DSC
     *
     * @param dsc the value for classmate.DSC
     *
     * @mbg.generated
     */
    public void setDsc(String dsc) {
        this.dsc = dsc == null ? null : dsc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmate.AUTHORITY
     *
     * @return the value of classmate.AUTHORITY
     *
     * @mbg.generated
     */
    public Integer getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmate.AUTHORITY
     *
     * @param authority the value for classmate.AUTHORITY
     *
     * @mbg.generated
     */
    public void setAuthority(Integer authority) {
        this.authority = authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classmate.HEAD_IMG
     *
     * @return the value of classmate.HEAD_IMG
     *
     * @mbg.generated
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classmate.HEAD_IMG
     *
     * @param headImg the value for classmate.HEAD_IMG
     *
     * @mbg.generated
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }
}