package cap.mvc.model;

public class Comments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.COMM_ID
     *
     * @mbg.generated
     */
    private Long commId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.STU_NMB
     *
     * @mbg.generated
     */
    private Integer stuNmb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.PAGE_ID
     *
     * @mbg.generated
     */
    private Long pageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.MSG
     *
     * @mbg.generated
     */
    private String msg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.COMM_ID
     *
     * @return the value of comments.COMM_ID
     *
     * @mbg.generated
     */
    public Long getCommId() {
        return commId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.COMM_ID
     *
     * @param commId the value for comments.COMM_ID
     *
     * @mbg.generated
     */
    public void setCommId(Long commId) {
        this.commId = commId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.STU_NMB
     *
     * @return the value of comments.STU_NMB
     *
     * @mbg.generated
     */
    public Integer getStuNmb() {
        return stuNmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.STU_NMB
     *
     * @param stuNmb the value for comments.STU_NMB
     *
     * @mbg.generated
     */
    public void setStuNmb(Integer stuNmb) {
        this.stuNmb = stuNmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.PAGE_ID
     *
     * @return the value of comments.PAGE_ID
     *
     * @mbg.generated
     */
    public Long getPageId() {
        return pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.PAGE_ID
     *
     * @param pageId the value for comments.PAGE_ID
     *
     * @mbg.generated
     */
    public void setPageId(Long pageId) {
        this.pageId = pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.MSG
     *
     * @return the value of comments.MSG
     *
     * @mbg.generated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.MSG
     *
     * @param msg the value for comments.MSG
     *
     * @mbg.generated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }
}