package cap.mvc.model;

public class Event {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.CODE
     *
     * @mbg.generated
     */
    private Integer code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.IMGAGES_PATH
     *
     * @mbg.generated
     */
    private String imgagesPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.EDITOR
     *
     * @mbg.generated
     */
    private String editor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.DT
     *
     * @mbg.generated
     */
    private Long dt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.STU_NMB
     *
     * @mbg.generated
     */
    private Integer stuNmb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.ISPASS
     *
     * @mbg.generated
     */
    private Integer ispass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.CODE
     *
     * @return the value of event.CODE
     *
     * @mbg.generated
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.CODE
     *
     * @param code the value for event.CODE
     *
     * @mbg.generated
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.TITLE
     *
     * @return the value of event.TITLE
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.TITLE
     *
     * @param title the value for event.TITLE
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.CONTENT
     *
     * @return the value of event.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.CONTENT
     *
     * @param content the value for event.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.IMGAGES_PATH
     *
     * @return the value of event.IMGAGES_PATH
     *
     * @mbg.generated
     */
    public String getImgagesPath() {
        return imgagesPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.IMGAGES_PATH
     *
     * @param imgagesPath the value for event.IMGAGES_PATH
     *
     * @mbg.generated
     */
    public void setImgagesPath(String imgagesPath) {
        this.imgagesPath = imgagesPath == null ? null : imgagesPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.EDITOR
     *
     * @return the value of event.EDITOR
     *
     * @mbg.generated
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.EDITOR
     *
     * @param editor the value for event.EDITOR
     *
     * @mbg.generated
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.DT
     *
     * @return the value of event.DT
     *
     * @mbg.generated
     */
    public Long getDt() {
        return dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.DT
     *
     * @param dt the value for event.DT
     *
     * @mbg.generated
     */
    public void setDt(Long dt) {
        this.dt = dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.STU_NMB
     *
     * @return the value of event.STU_NMB
     *
     * @mbg.generated
     */
    public Integer getStuNmb() {
        return stuNmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.STU_NMB
     *
     * @param stuNmb the value for event.STU_NMB
     *
     * @mbg.generated
     */
    public void setStuNmb(Integer stuNmb) {
        this.stuNmb = stuNmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.ISPASS
     *
     * @return the value of event.ISPASS
     *
     * @mbg.generated
     */
    public Integer getIspass() {
        return ispass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.ISPASS
     *
     * @param ispass the value for event.ISPASS
     *
     * @mbg.generated
     */
    public void setIspass(Integer ispass) {
        this.ispass = ispass;
    }
}