package cap.mvc.model;

public class Images {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.PIC_PATH
     *
     * @mbg.generated
     */
    private String picPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.DSC
     *
     * @mbg.generated
     */
    private String dsc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.GRO
     *
     * @mbg.generated
     */
    private Integer gro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.DT
     *
     * @mbg.generated
     */
    private Long dt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.ID
     *
     * @return the value of images.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.ID
     *
     * @param id the value for images.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.PIC_PATH
     *
     * @return the value of images.PIC_PATH
     *
     * @mbg.generated
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.PIC_PATH
     *
     * @param picPath the value for images.PIC_PATH
     *
     * @mbg.generated
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.DSC
     *
     * @return the value of images.DSC
     *
     * @mbg.generated
     */
    public String getDsc() {
        return dsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.DSC
     *
     * @param dsc the value for images.DSC
     *
     * @mbg.generated
     */
    public void setDsc(String dsc) {
        this.dsc = dsc == null ? null : dsc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.GRO
     *
     * @return the value of images.GRO
     *
     * @mbg.generated
     */
    public Integer getGro() {
        return gro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.GRO
     *
     * @param gro the value for images.GRO
     *
     * @mbg.generated
     */
    public void setGro(Integer gro) {
        this.gro = gro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.DT
     *
     * @return the value of images.DT
     *
     * @mbg.generated
     */
    public Long getDt() {
        return dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.DT
     *
     * @param dt the value for images.DT
     *
     * @mbg.generated
     */
    public void setDt(Long dt) {
        this.dt = dt;
    }
}