package cap.mvc.model;

public class Page {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.PAGE_ID
     *
     * @mbg.generated
     */
    private Long pageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.MODEl
     *
     * @mbg.generated
     */
    private Integer model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.DSC
     *
     * @mbg.generated
     */
    private String dsc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.BIRTHDAY
     *
     * @mbg.generated
     */
    private Long birthday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.PAGE_ID
     *
     * @return the value of page.PAGE_ID
     *
     * @mbg.generated
     */
    public Long getPageId() {
        return pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.PAGE_ID
     *
     * @param pageId the value for page.PAGE_ID
     *
     * @mbg.generated
     */
    public void setPageId(Long pageId) {
        this.pageId = pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.MODEl
     *
     * @return the value of page.MODEl
     *
     * @mbg.generated
     */
    public Integer getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.MODEl
     *
     * @param model the value for page.MODEl
     *
     * @mbg.generated
     */
    public void setModel(Integer model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.DSC
     *
     * @return the value of page.DSC
     *
     * @mbg.generated
     */
    public String getDsc() {
        return dsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.DSC
     *
     * @param dsc the value for page.DSC
     *
     * @mbg.generated
     */
    public void setDsc(String dsc) {
        this.dsc = dsc == null ? null : dsc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.BIRTHDAY
     *
     * @return the value of page.BIRTHDAY
     *
     * @mbg.generated
     */
    public Long getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.BIRTHDAY
     *
     * @param birthday the value for page.BIRTHDAY
     *
     * @mbg.generated
     */
    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }
}