package cap.mvc.dao.mapper;

import cap.mvc.dao.mapper.custom.CustomClassmateMapper;
import cap.mvc.model.Classmate;

public interface ClassmateMapper extends CustomClassmateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classmate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer stuNmb);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classmate
     *
     * @mbg.generated
     */
    int insert(Classmate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classmate
     *
     * @mbg.generated
     */
    int insertSelective(Classmate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classmate
     *
     * @mbg.generated
     */
    Classmate selectByPrimaryKey(Integer stuNmb);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classmate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Classmate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classmate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Classmate record);
}