package cap.mvc.dao.mapper;

import cap.mvc.dao.mapper.custom.CustomPageMapper;
import cap.mvc.model.Page;

public interface PageMapper extends CustomPageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long pageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated
     */
    int insert(Page record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated
     */
    int insertSelective(Page record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated
     */
    Page selectByPrimaryKey(Long pageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Page record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Page record);
}